tasks:
- init: ./mvnw package -DskipTests
  command: java -jar target/*.jar
- init: ./scripts/intellij-indexing.sh
  name: IntellIJ indexing
 
# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot

jetbrains:
  plugins:
    - com.haulmont.jpab
