tasks:
- init: ./mvnw package -DskipTests
  command: java -jar -Dspring.profiles.active=preview target/*.jar

# exposed ports
ports:
- port: 8090
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
