image:
  file: Dockerfile

tasks:
# - init: ./mvnw package -DskipTests
#   command: java -jar target/*.jar
- command: echo "Hello GED Warrior!"

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - pivotal.vscode-spring-boot
