image:
  file: .gitpod/Dockerfile

tasks:
  - init: ./mvnw clean install -U -DskipTests
    command: ./mvnw spring-boot:run
    name: Run PetClinic app
  - command: mob moo
    name: Mob Control
    openIn: bottom
    openMode: split-right

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

jetbrains:
  intellij:
    plugins:
      - com.haulmont.jpab
    prebuilds:
      version: both
