image:
  file: Dockerfile

tasks:
# - init: ./mvnw package -DskipTests
#   command: java -jar target/*.jar
- command: echo "Hello GED Warrior!"

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-debug@0.23.0:3ARqL3kPh1J1SwpVjYUjqw==
    - redhat.java@0.54.2:Q60n5quUtfd1EcwzkRq96A==
    - vscjava.vscode-java-test@0.22.0:BlvjRRJyZszeJzIS+xEHIA==
