ports:
- port: 8080
  onOpen: open-preview
# start up tasks
tasks:
- init: ./mvnw package -DskipTests
  command: java -jar target/*.jar

vscode:
  extensions:
    - vscjava.vscode-java-test@0.19.0:xwfuoJBZpCcLrZ33G3zkXA==